# Time-based ranges
startTimes: [50, 80, 110, 140, 170, 200, 230, 260, 290, 320, 350, 380, 410, 440, 470]
selectTimes: [30]
searchTimes: [30, 80, 130, 180]
longMovingAvgTimes: [140]

# Filter-based ranges
sellCutOffPerc: [0.93]
lowerPriceToLongAvgBuyIn: [0.92]
higherPriceToLongAvgBuyIn: [1.02]
timeFrameForUpwardLongAvg: [40]
timeFrameForOscillator: [110]
maxPERatios: [25]
aboveAvgRatingPricePerc: [1.0]
timeFrameForUpwardShortPrice: [1]
maxRSI: [100.0]
minMarketCap: [50.0]
maxMarketCap: [2000000.0]
minRatesOfAvgInc: [1.1]
minRatings: [3.75]
maxRatings: [4.6]
riskFreeRate: [0.1]

# Weight Ranges
movingAvgGapWeight: [0.20]
reversionToMeanWeight: [0.15]
ratingWeight: [0.20]
upwardIncRateWeight: [0.15]
rvolWeight: [0.10]
pegWeight: [0.10]
volatilityCompressionWeight: [0.10]

# Global Project Settings
sectors: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60]
exchanges: ["TASE", "NYSE", "NasdaqGS", "NasdaqGM", "NasdaqCM", "AMEX"]
outputPath: "C:/Users/NF/IdeaProjects/stock-analyzer-java/output"
